### ISSUE TITLE
Allow for Narrowed Element Types

### ISSUE THREAD

**Issue by almann** [amzn/ion-element-kotlin#11]
The [IonValue][1] API has a type hierarchy for the specific types of values and requires
narrowing to those type (e.g. [IonInt][2]) to get at specific typed data.

```java
IonValue v = /* An IonInt */;
IonInt i = (IonInt) i;

i.longValue();
```

A conscience design choice in [IonElement][3] was to avoid a lot of type narrowing to access the
Ion data.  However, it is the case that some code may want to *assert* a particular Ion data type
and leverage Kotlin/Java's static typing in downstream code.

We have limited versions of this for aggregates versus the scalar API surface with:

* [IonElementContainer][4] -`IonElement.containerValue`
* [StructIonElement][5] - `IonElement.structValue`

One way of addressing this use case is to have *narrowed* interfaces for the specific Ion types
(e.g. `BoolElement`, `IntElement`, `StringElement`) and some slightly wider variants for common
overlaping types (e.g. `TextElement` that is derived by both `StringElement` and `SymbolElement`).

`IonElement` would still be the catch all type for any user that wanted to operate on data in
a very late bound way, but would ***not*** be related to the other narrowed `XXXElement` types.
The narrowed `XXXElement` types would, however, be aligned API-wise to the APIs that are relevant
in `IonElement`.  `IonElement` would also be extended to have `asXXXElement(): XXXElement` APIs
to capture the narrowing (we may also consider adding nullable versions of said APIs).

For the [IonValue][1] API example above, the following would be the narrowed element equivalent:

```java
IonElement e = /* An element that happens to be an int */;
IntElement i = e.asIntElement(); // would throw if not the right type (but notice no narrowing)

i.longValue();
e.longValue(); // any API in a narrowed element exists in IonElement

IonElement e2 = i; // compile error! IntElement is not assignable to IonElement
```

Notice in the above API, the `IntElement` usage looks almost exactly like the `IonElement`.
The key difference is that `IntElement` only has the APIs relevant from `IonElement` for Ion
integers, and otherwise has no relationship.  It may make sense to refactor the common aspects
of all Ion values into a super interface (e.g. annotations, type, nullness), but this is not
strictly required.

The cost of this abstraction is a virtual method, an existing implementation of
`IonElement` need only implement the narrower interfaces (since they are subsumed by `IonElement`)
and can return `this` in the relevant `asXXXElement` APIs.  This cheap implementation strategy
does mean that technically a user having this implementation could merely cast to the narrowed
type, but such use case should be considered not supported and an implementation may choose to
*not* implement the narrowed interface and return a narrowed view of the `IonElement` as a distinct
type.  This implementation approach has the downside of costing an extra reference variable and/or
extra allocation.

[1]: https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/IonValue.java
[2]: https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/IonInt.java
[3]: https://github.com/amzn/ion-element-kotlin/blob/master/src/com/amazon/ionelement/api/IonElement.kt
[4]: https://github.com/amzn/ion-element-kotlin/blob/master/src/com/amazon/ionelement/api/IonElementContainer.kt
[5]: https://github.com/amzn/ion-element-kotlin/blob/master/src/com/amazon/ionelement/api/StructIonElement.kt

**Comment by almann** [comment]
A couple thoughts from discussion with various folks offline. We should be clear about the behavior of these APIs with respect to `null` Ion values of various types.

For a given type `T`, the `asTElement(): TElement` method should return a narrowed instance of `TElement` when the Ion type is *narrowable* with respect to `T` **and** is not a `null` value.  For all other cases this method should throw.  For the nullable case `asTElementNullable(): TElement?`, a `TElement` is returned similarly, but in the `null` value case where the type of the `null` is either `null` (i.e. `null.null`) or the type is *narrowable* with respect to `T`, then the return is a `null` ***reference***.  For all other cases the method should throw similarly.

For example, consider `TextElement` that is *narrowable* from a `string` and `symbol` value. Both `asTextElement` and `asTextElementNullable` would return a `TextElement` for non-null values of Ion type `string` or `symbol`.  For `asTextElementNullable`, a `null.null`, `null.symbol`, and `null.string` would return a `null` reference.  For all other cases an exception would be thrown.

The rationale for this behavior is to be consistent with the nullable properties on the `IonElement` interface, and while we *could* consider returning a non-null `TElement` for a typed null in this case, it would be confusing if a `null.null` were allowed to be a `TElement` whose type was contradictory to the asserted Ion type.  Furthermore, it would be confusing to have two distinct cases for valid `null` values, one of which returned an object and the other of which returned a `null` reference.

**Comment by almann** [comment]
Also, to clarify which type hierarchy seems reasonable here:

* `BoolElement`
* `IntElement`
* `FloatElement`
* `DecimalElement`
* `TimestampElement`
* `TextElement`
  - `SymbolElement`
  - `StringElement`
* `LobElement`
  - `ClobElement`
  - `BlobElement`
* `AggregateElement`
  - `SeqElement`
    * `SexpElement`
    * `ListElement`
  - `StructElement`

It is debatable whether `NumberElement` (as a parent of the numeric types) would be useful or not.

**Comment by dlurton** [comment]
Here's the current state of these changes on my local machine:  ![IonElement diagram](https://user-images.githubusercontent.com/2142212/84347105-8aaf9c80-ab66-11ea-9f7a-002798825dcf.png)

From `IonElement`:
- A super-interface named `Element` was extracted from `IonElement` containing all of the functionality for manipulating annotations, metas and writing using an `IonWriter`, etc.
    - The `*Value` and `*ValueOrNull` properties for the collection types were removed
    - `asNarrow()` and `asNarrowOrNull()` functions were added
          - Note: it seems a little odd to me that these would be functions while the remaining `*Value` and `*ValueOrNull` accessors remain properties, but I'm not sure how others feel about that.
    - Added `NarrowElement` and `NarrowerElement` interfaces like `TextElement`, `StringElement` as well as `LobElement`, `BlobElement` and `ClobElement`.

**Comment by almann** [comment]
This looks reasonable, I like `Element` as the base common interface for all things Ion-y.

Minor, but for `StructElement`, I might suggest the following for the field accessors to be consistent:

```kotlin
interface StructElement : ContainerElement {
  operator fun get(key: String): IonElement
  fun getOrNull(key: String): IonElement?

  fun getAll(key: String): Iterable<IonElement>
  fun getAllOrNull(key: String): Iterable<IonElement>?
}
```

**Comment by dlurton** [comment]
is `getAllOrNull` needed though?  can't just `getAll` return an empty list in that case?  Or should `getAll` throw when no matching fields are present?

**Comment by dlurton** [comment]
Implemented here: https://github.com/amzn/ion-element-kotlin/pull/22
