### ISSUE TITLE
Reconsider the Factoring of StructIonElement and IonElementContainer

### ISSUE THREAD

**Issue by almann** [amzn/ion-element-kotlin#12]
Given #11 , we should consider how to deal with these two types.  For backwards compatibility they can exist, but given how flat the `IonElement` API is, these two types feel a bit out of place.  If we do #11, we will have in addition `StructElement`, `ListElement`, and `SexpElement`.  There may be a common `SeqElement` to cover the common ordered collection case, and possibly a `CollectionElement` to cover all of the aggregates (e.g. the value iterable).

Personally, I think we should flatten the API surface of these two methods into `IonElement` and deprecate the particular `xxxValue` properties for the aggregates.

**Comment by dlurton** [comment]
Implemented here: https://github.com/amzn/ion-element-kotlin/pull/22
