### ISSUE TITLE
Incorrect receiver type of `.toIonValue` for `IonElement`

### ISSUE THREAD

**Issue by dlurton** [amzn/ion-element-kotlin#35]
During the `v0.2.0` release we changed the receiver type of this function from `IonElement` to `AnyElement`.  It probably should have remained `IonElement`.

https://github.com/amzn/ion-element-kotlin/blob/bb47f699bf87072a57287f1b945b52f72487b835/src/com/amazon/ionelement/api/IonUtils.kt#L29

This is a minor annoyance because now instead of calling `.toIonValue` directly, it must first be converted to `AnyElement`:

```Kotlin
val someElement: IonElement = ...
val someValue = someElement.asAnyElement().toIonValue()

// but we should just be able to:
val someValue = someElement.toIonValue()
```

**Comment by popematt** [comment]
Fixed by https://github.com/amzn/ion-element-kotlin/commit/d3dc8bc036808e08a5f930c10b3a599552c4c0ea
