### ISSUE TITLE
Add API Documentation Around `*Element` Inheritance

### ISSUE THREAD

**Issue by almann** [amzn/ion-element-kotlin#55]
I've noticed some code around that does explicit narrowing from `AnyElement` to things like `ListElement`.  I don't believe that this is technically documented to be required by any implementation.  If it is the case, we should document this as it is an important detail.

**Comment by dlurton** [comment]
Suggested verbiage is along the lines of: 

```
An AnyElement for a given Ion type is required to also implement the respective *Element interface...
```
