### ISSUE TITLE
Publish Javadoc to javadoc.io

### ISSUE THREAD

**Issue by almann** [amzn/ion-element-kotlin#56]
It would be nice if the following worked:

https://www.javadoc.io/doc/com.amazon.ion/ion-element/latest/index.html

Ion Java does publish a Javadoc artifact:

https://www.javadoc.io/doc/com.amazon.ion/ion-java/latest/index.html

**Comment by popematt** [comment]
https://www.javadoc.io/doc/com.amazon.ion/ion-element/latest/com/amazon/ionelement/api/package-summary.html 🥳
